Backend + Group: Fix setting tiled position by mouse
It gave an AttributeError:

```python
    self.group.layout.focused = index2
AttributeError: can't set attribute 'focused'
```

Let's just use the layout swap method instead of the hacky
.clients (which would only work for clientlist). To avoid duplicated
code let's make a swap method in group. This checks if the layout also
supports a swap method to avoid erroring out

Signed-off-by: jwijenbergh <qtile@jwijenbergh.com>