idlerpg: set json/xml flags explicitly
...instead of using the defaults framework.

These are really hard coded settings for this widget, users can't really
change them. Add to that that this wasn't working (since json was already
set, it was masked), so the idlerpg widget always tried to parse the
response as json, and always failed:

2022-11-23 16:33:11,667 ERROR libqtile base.py:on_done():L789 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/widget/base.py", line 786, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/widget/generic_poll_text.py", line 85, in poll
    body = self.fetch()
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/widget/generic_poll_text.py", line 74, in fetch
    body = json.loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Let's just explicitly set these in __init__ after all the other
initialization has completed.

I have no idea when this broke, because I swear this used to work. But I
haven't had time to debug it until recently :)

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>