tests: fix a couple of config instantiations
622b69428c3b ("Manage Qtile subprocess better") rearranged the way configs
get instantiated, and run_qtile() now automatically instantiates them if
the class object is passed.

However, these two tests were making modifications to the class object,
which were then getting discarded by the instantiation in run_qtile().

We can't just drop this instantiation, because Config.load expects a self
argument:

Traceback (most recent call last):
  File "/home/tycho/packages/qtile/libqtile/core/manager.py", line 104, in load_config
    self.config.load()
TypeError: load() missing 1 required positional argument: 'self'

which means if we're going to make local modifications to config objects, we
need to instantiate them before we do so.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>