wayland: keep a downcasted Core in Window
Window wants to call wayland-specific Core methods, but qtile.core is the
backend base type, not a wayland type. Let's keep a downcasted copy and
avoid some type errors:

    libqtile/backend/wayland/window.py:147: error: "Core" has no attribute "check_inhibited"; maybe "_inhibited"?  [attr-defined]
    libqtile/backend/wayland/window.py:151: error: "Core" has no attribute "check_inhibited"; maybe "_inhibited"?  [attr-defined]
    libqtile/backend/wayland/window.py:236: error: "Core" has no attribute "focus_window"  [attr-defined]
    libqtile/backend/wayland/window.py:715: error: "Core" has no attribute "check_inhibited"; maybe "_inhibited"?  [attr-defined]
    libqtile/backend/wayland/window.py:849: error: "Core" has no attribute "qw_cursor"  [attr-defined]
    libqtile/backend/wayland/window.py:850: error: "Core" has no attribute "qw_cursor"  [attr-defined]

(x11 doesn't have this problem because x11 has substantially less type
checking in general, and specifically on qtile.core.)

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>