move mpris2 dbus initialization to configure()
The problem here is that when the widget constructor is called (in the
config file), the manager's main function hasn't been called yet, so it
hasn't set up our proxy dbus loop. This ends up causing:

[0m[33m2017-03-17 20:58:49,810 [1m[33mlibqtile confreader.py:__init__():L67 [0m Caught exception in configuration:

Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.5/site-packages/libqtile/confreader.py", line 55, in __init__
    config = __import__(os.path.basename(fname)[:-3])
  File "/home/tycho/.qtile/config.py", line 118, in <module>
    **widget_defaults
  File "/home/tycho/.local/lib/python3.5/site-packages/libqtile/widget/mpris2widget.py", line 68, in __init__
    '/org/mpris/MediaPlayer2')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 148, in add_signal_receiver
    path, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 400, in add_signal_receiver
    self._require_main_loop()
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)

The solution here is to wait until we have actually initialized the main
loop, so GDbusMainLoop does the right thing and all is happy.

Closes #1025

Signed-off-by: Tycho Andersen <tycho@tycho.ws>