[wayland] convert keycodes to keysyms
The keycode to keysym code is missing from the backend so
using a keycode in the config results in qtile failing to
start with the following error:

AttributeError: cffi library 'libqtile.backend.wayland._ffi'
has no function, constant or global variable named 'qwu_get_sym_from_code'.
Did you mean: 'qwu_keysym_from_name'?

Fixes #5700