fix(mypy): _build_config.py causes unused 'type: ignore' error
Precommit output:
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

libqtile/__init__.py:61: error: Unused "type: ignore" comment  [unused-ignore]
Found 1 error in 1 file (checked 1 source file)