prepare for cairocffi's in-line distribution
I really don't think we should need the cast patches to pangocffi, but it
seems we do or we get:

2023-06-01 17:25:05,283 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 205, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 230, in async_loop
    self.load_config(initial=True)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 143, in load_config
    self._process_screens(reloading=not initial)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/core/manager.py", line 382, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/config.py", line 481, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/bar.py", line 311, in _configure
    self._remove_crashed_widgets()
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/bar.py", line 359, in _remove_crashed_widgets
    crash._configure(self.qtile, self)
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/widget/base.py", line 541, in _configure
    self.layout = self.drawer.textlayout(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/backend/base.py", line 853, in textlayout
    textlayout = drawer.TextLayout(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/drawer.py", line 43, in __init__
    layout = drawer.ctx.create_layout()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/pangocffi.py", line 62, in create_layout
    return PangoLayout(cairo_t._pointer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tycho/.local/lib/python3.11/site-packages/libqtile/pangocffi.py", line 89, in __init__
    self._pointer = pangocairo.pango_cairo_create_layout(cairo_t)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: initializer for ctype 'struct _cairo *' must be a pointer to same type, not cdata 'cairo_t *'

These should be safe even on old cairocffi's, so let's ship them now so the
new cairocffi release doesn't break everyone like the xcffib one did :)
(whoops!)

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>