Add PyGObject to dev requirements
PyGObject is used in:
- test/scripts/window.py
- test/layouts/test_common.py
- test/backend/wayland/test_window.py

But not listed in requirements-dev.txt. This causes tests to fail with:
ModuleNotFoundError: No module named 'gi'

Add PyGObject to requirements-dev.txt to automatically installi it into dev venv.