widget: don't return an error when calculating length
If a widget's length calculation has a bug and raises an exception, we
silently swallow it via @property, and it shows up as an AttributeError:

    2025-09-02 20:26:46,949 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
    Traceback (most recent call last):
      File "/usr/lib/python3.13/asyncio/events.py", line 89, in _run
        self._context.run(self._callback, *self._args)
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/libqtile/core/manager.py", line 997, in f
        func(*args)
        ~~~~^^^^^^^
      File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 622, in _actual_draw
        self._resize(self._length, self.widgets)
        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 465, in _resize
        stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                                ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 465, in <genexpr>
        stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                                    ^^^^^^^^
      File "/usr/lib/python3.13/site-packages/libqtile/command/base.py", line 283, in __getattr__
        raise AttributeError(f"{self.__class__} has no attribute {name}")
    AttributeError: <class 'libqtile.widget.groupbox.GroupBox'> has no attribute length. Did you mean: '_length'?

Let's catch these exceptions and log them, so we can try and fix these
problems.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>