test/migrate: only run check test if there really is one
We are getting:

    _________________________ test_check_all_migrations[ModuleRenames-no-check-test] _________________________

    migration_tester = <test.migrate.conftest.MigrationTester object at 0x7f306e2e78a0>

        @pytest.mark.parametrize("migration_tester", migration_tests, indirect=True, ids=migration_ids)
        def test_check_all_migrations(migration_tester):
    >       migration_tester.assert_check()

    migrate/test_check_migrations.py:51:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = <test.migrate.conftest.MigrationTester object at 0x7f306e2e78a0>

        def assert_check(self):
            if not self.test.source:
    >           assert False, f"{self.test_id} has no Check test."
    E           AssertionError: ModuleRenames has no Check test.
    E           assert False

    migrate/conftest.py:95: AssertionError

when we actually run the migration tests in CI, which is true, because
ModuleRenames does not in fact have any Check tests.

But that's fine, we can just skip running this test in
test_check_migrations.py, since it will be run by test_migrations.py.

Fixes #4868

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>