x11: add fullscreen property to _Window
In the process of adding type checking to some other things I will probably
send soon, I noticed:

libqtile/backend/x11/window.py:898: error: "_Window" has no attribute "fullscreen"  [attr-defined]
libqtile/backend/x11/window.py:906: error: "_Window" has no attribute "fullscreen"  [attr-defined]

this code has been around for a long time, so the fact that it hasn't
crashed suggests that it's probably dead (or suggests that people do not
actually extend WM_SIZE_HINTS in practice? I couldn't find the original
application that motivated this code). Anyway, let's make sure it doesn't
crash.