window: require Internal windows to define .focus()
libqtile/bar.py:625: error: "Internal" has no attribute "focus"  [attr-defined]

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>