docs: don't render config table if there's nothing in it
For Qtile "Configurable" items, if there's nothing in the table, sphinx
complains:

   Warning, treated as error:
  <QtileClass>:1:Insufficient data supplied (1 row(s)); no data remaining for table body, required by "list-table" directive.

  .. list-table::
      :widths: 20 20 60
      :header-rows: 1

      * - key
        - default
        - description
  ERROR: InvocationError for command /home/runner/work/qtile/qtile/.tox/docs/bin/python3 setup.py build_sphinx -W (exited with code 1)

that the table is empty so we shouldn't render it. That seems reasonable, so
let's not render it if it is empty.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>