Don't AttributeError when set_group-ing Screen with no group
`cmd_reconfigure_screens` can error:

```
    File "/home/mcol/git/qtile/libqtile/core/manager.py", line 325, in cmd_reconfigure_screens
	self._process_screens()
    File "/home/mcol/git/qtile/libqtile/core/manager.py", line 312, in _process_screens
	scr._configure(self, i, x, y, w, h, grp)
    File "/home/mcol/git/qtile/libqtile/config.py", line 290, in _configure
	self.set_group(group)
    File "/home/mcol/git/qtile/libqtile/config.py", line 349, in set_group
	g1 = self.group
AttributeError: 'Screen' object has no attribute 'group'
```

This happens if `Screen.set_group` is called when that screen has no
group, as rather than the group being `None` it is absent if the screen
has no group, and we need to handle that slightly differently.