wayland: move floating logic Base -> Window
There are a bunch of type errors:

    libqtile/backend/wayland/window.py:84: error: "Base" has no attribute "get_new_layer"  [attr-defined]
    libqtile/backend/wayland/window.py:84: error: "Base" has no attribute "_float_state"  [attr-defined]
    libqtile/backend/wayland/window.py:91: error: "Base" has no attribute "get_new_layer"  [attr-defined]
    libqtile/backend/wayland/window.py:91: error: "Base" has no attribute "_float_state"  [attr-defined]
    libqtile/backend/wayland/window.py:155: error: "Base" has no attribute "_float_width"  [attr-defined]
    libqtile/backend/wayland/window.py:156: error: "Base" has no attribute "_float_height"  [attr-defined]
    libqtile/backend/wayland/window.py:170: error: "Base" has no attribute "_float_state"  [attr-defined]
    libqtile/backend/wayland/window.py:171: error: "Base" has no attribute "_float_state"  [attr-defined]
    libqtile/backend/wayland/window.py:172: error: "Base" has no attribute "_float_state"  [attr-defined]
    libqtile/backend/wayland/window.py:173: error: "Base" has no attribute "_float_state"  [attr-defined]

all of these things are floating-specific, which means they are client
Windows, and don't need to be on the base class. Move them to Window.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>