x11: fix some type errors in drawer
With the cmd_ patch dropped, I get:

    libqtile/backend/x11/drawer.py:31: error: "Core" has no attribute "conn"  [attr-defined]
    libqtile/backend/x11/drawer.py:156: error: "Core" has no attribute "conn"  [attr-defined]

This makes sense: only the x11 backend has a .conn attribute, so the Core
object can't export it.

Since drawers are all created via create_drawer(), and we have a connection
in hand there, let's just pass that directly to the drawer instead, so we
don't have to use the indirection of qtile.

Also, only the x11 backend uses the qtile argument at all (but doesn't
after this patch), so we can drop it, hopefully reducing some circularity.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>