fix(_process_screens): finalize bar when it raises an exception in configure
The problem is that when the screen is configured and the bar raises an
exception, the screen will not be added to 'self.screens' which means that
the next time in _process_screens(), the bar will not finalize which will
throw errors when trying to get 'length' in CALCULATED _TextBox widgets
since it depends on the call to the layout which already finalize.

Traceback (most recent call last):
  File "/usr/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/core/manager.py", line 990, in f
    func(*args)
    ~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 612, in _actual_draw
    self._resize(self.length, self.widgets)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 455, in _resize
    stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                            ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 455, in <genexpr>
    stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                                ^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/widget/base.py", line 188, in length
    return int(self.calculate_length())
               ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/libqtile/widget/base.py", line 639, in calculate_length
    return min(self.layout.width, self.bar.length) + self.actual_padding * 2
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/backend/base/drawer.py", line 415, in width
    return self.layout.get_pixel_size()[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType