fix unknown keysym behavior
instead of throwing an exception like:

Traceback (most recent call last):
  File "qtile/libqtile/backend/x11/xcore.py", line 245, in _xpoll
    ret = target(event)
  File "qtile/libqtile/backend/x11/xcore.py", line 493, in handle_KeyPress
    self.qtile.process_key_event(keysym, event.state & self._valid_mask)
  File "qtile/libqtile/core/manager.py", line 349, in process_key_event
    key = self.keys_map[(keysym, mask)]
KeyError: (65515, 0)

Let's just use the code that's already here and ignore an error.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>