ci/release: pass --config-setting backend=wayland
At some point this must have become required, but our release script didn't
pass it, so it failed with:

    INFO:auditwheel.main_show:This does not look like a platform wheel, no ELF executable or shared library file (including compiled Python C extension) found in the wheel archive
    Error: Process completed with exit code 1.

which is correct, because we didn't actually include the wayland .so.
Whoops.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>