Revert "Move border painting with X pixel cache into X backend"
This reverts commit 174c9faf1065c9cd30ea3b0e520b65a78da4da57.

2020-08-26 22:27:12,861 ERROR libqtile xcore.py:_xpoll():L278 Got an exception in poll loop
Traceback (most recent call last):
  File "qtile/libqtile/backend/x11/xcore.py", line 246, in _xpoll
    ret = target(event)
  File "qtile/libqtile/window.py", line 1270, in handle_PropertyNotify
    self.update_state()
  File "qtile/libqtile/window.py", line 330, in update_state
    setattr(self, s, (s in state))
  File "qtile/libqtile/window.py", line 881, in fullscreen
    new_float_state=FULLSCREEN
  File "qtile/libqtile/window.py", line 1049, in _enablefloating
    self._reconfigure_floating(new_float_state=new_float_state)
  File "qtile/libqtile/window.py", line 1039, in _reconfigure_floating
    self.group.mark_floating(self, True)
  File "qtile/libqtile/group.py", line 326, in mark_floating
    self.layout_all()
  File "qtile/libqtile/group.py", line 164, in layout_all
    self.floating_layout.layout(floating, screen_rect)
  File "qtile/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen_rect)
  File "qtile/libqtile/layout/floating.py", line 235, in configure
    client.user_placed_window_setup(bc, bw)
  File "qtile/libqtile/window.py", line 501, in user_placed_window_setup
    self.window.set_attribute(borderpixel=borderpixel)
  File "qtile/libqtile/backend/x11/xcbq.py", line 630, in set_attribute
    self.wid, mask, values
  File ".local/lib/python3.7/site-packages/xcffib/xproto.py", line 2591, in ChangeWindowAttributes
    buf.write(struct.pack("=I", border_pixel))
struct.error: required argument is not an integer
2020-08-26 22:27:15,163 ERROR libqtile xcore.py:_xpoll():L278 Got an exception in poll loop
Traceback (most recent call last):
  File "qtile/libqtile/backend/x11/xcore.py", line 246, in _xpoll
    ret = target(event)
  File "qtile/libqtile/backend/x11/xcore.py", line 555, in handle_ButtonPress
    button_code, state, event.event_x, event.event_y, event
  File "qtile/libqtile/core/manager.py", line 777, in process_button_click
    self.cmd_focus_by_click(event)
  File "qtile/libqtile/core/manager.py", line 752, in cmd_focus_by_click
    self.current_group.focus(self.windows_map.get(wnd), False)
  File "qtile/libqtile/group.py", line 235, in focus
    self.layout_all(warp)
  File "qtile/libqtile/group.py", line 164, in layout_all
    self.floating_layout.layout(floating, screen_rect)
  File "qtile/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen_rect)
  File "qtile/libqtile/layout/floating.py", line 235, in configure
    client.user_placed_window_setup(bc, bw)
  File "qtile/libqtile/window.py", line 501, in user_placed_window_setup
    self.window.set_attribute(borderpixel=borderpixel)
  File "qtile/libqtile/backend/x11/xcbq.py", line 630, in set_attribute
    self.wid, mask, values
  File ".local/lib/python3.7/site-packages/xcffib/xproto.py", line 2591, in ChangeWindowAttributes
    buf.write(struct.pack("=I", border_pixel))
struct.error: required argument is not an integer