Revert "Match: Allow any class of a client to match"
This reverts commit a6ee6a9cfe63afd89f2c85495b9b88d0e483f1eb.

With this patch, I get:

2020-07-27 20:18:32,408 libqtile hook.py:fire():L367 [0m Error in hook client_new
Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.8/site-packages/libqtile/hook.py", line 365, in fire
    i(*args, **kwargs)
  File "/home/tycho/.local/lib/python3.8/site-packages/libqtile/dgroups.py", line 169, in _add
    if rule.matches(client):
  File "/home/tycho/.local/lib/python3.8/site-packages/libqtile/config.py", line 664, in matches
    return self.match.compare(w)
  File "/home/tycho/.local/lib/python3.8/site-packages/libqtile/config.py", line 619, in compare
    match = getattr(rule, 'match', None) or getattr(rule, 'count')
AttributeError: 'int' object has no attribute 'count'[0m

Let's revert it for now, maybe someone can fix it later.

Closes #1841