bar: push x11 _grab_click() into x11 backend
Because of how we focus windows in x11 when people click on a root window,
we need to call _grab_click(). But we can't do that on a base.Window:

    libqtile/bar.py:544: error: "Window" has no attribute "_grab_click"  [attr-defined]

We do this in a couple of places, so commonize those calls.

Perhaps we should make a backend specific focus_screen() instead and
override this there? But wayland doesn't have this concept, so perhaps
that's more noise than it's worth.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>