fix(VerticalClock): check for mix values in lists
Most importantly set the padding as the average of list of fontsize
due to an error when calculating the padding dividing by a list.

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/libqtile/config.py", line 518, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 366, in _configure
    self._resize(self._length, self.widgets)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/bar.py", line 514, in _resize
    offset += i.length
              ^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/widget/base.py", line 181, in length
    return int(self.calculate_length())
               ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/libqtile/widget/vertical_clock.py", line 97, in calculate_length
    return sum(l.height + self.actual_padding for l in self.layouts) + self.actual_padding
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/widget/vertical_clock.py", line 97, in <genexpr>
    return sum(l.height + self.actual_padding for l in self.layouts) + self.actual_padding
                          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/widget/base.py", line 563, in actual_padding
    return self.fontsize // 2
           ~~~~~~~~~~~~~~^^~~
TypeError: unsupported operand type(s) for //: 'list' and 'int'