idle_inhibit: use is_visible() to detect visibility
libqtile/backend/base/idle_inhibit.py:71: error: "Window" has no attribute "visible"  [attr-defined]

x11 does not have the member, but it does have the function because the
base class requires it. Let's use the function.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>