ci: fix python-version warning in `check`
when I try to specify the python-version, i get some inscrutable error
like:

    Traceback (most recent call last):
      File "/home/runner/.cache/pre-commit/repozetpwfq2/py_env-python3.12/lib/python3.12/site-packages/flake8/plugins/finder.py", line 291, in _load_plugin
        obj = plugin.entry_point.load()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
        module = import_module(match.group('module'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/runner/.cache/pre-commit/repozetpwfq2/py_env-python3.12/lib/python3.12/site-packages/logging_format/api.py", line 6, in <module>
        from logging_format.whitelist import Whitelist
      File "/home/runner/.cache/pre-commit/repozetpwfq2/py_env-python3.12/lib/python3.12/site-packages/logging_format/whitelist.py", line 5, in <module>
        from pkg_resources import iter_entry_points
    ModuleNotFoundError: No module named 'pkg_resources'

since we're using the host python anyway, let's just not invoke the
setup-python action at all.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>