pyproject: add more build requirements
CI is complaining (but not failing):

    * Building sdist...
      /tmp/build-env-xomi1h1m/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:31: RuntimeWarning:
      ERROR: setuptools==0.1.dev1+g59b329a is used in combination with setuptools_scm>=8.x

      Your build configuration is incomplete and previously worked by accident!
      setuptools_scm requires setuptools>=61

      Suggested workaround if applicable:
       - migrating from the deprecated setup_requires mechanism to pep517/518
         and using a pyproject.toml to declare build dependencies
         which are reliably pre-installed before running the build tools

This seems to fix it.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>