drop old migrations
our official policy is that all migrations at least two years old. at the
time of this writing:

    $ git describe --tags --abbrev=0 $(git log -n 1 --before="2 years ago" --pretty=format:"%H")
    v0.22.1

everything before v0.22.1 can be deleted.

My real motivation for this is that this code does not support transitive
renames, and in future patches for asyncio we want to go ThreadedPollText
-> ThreadPoolText -> BackgroundPoll, which causes:

    Checking if config is valid python...
    Traceback (most recent call last):
      File "/home/runner/work/qtile/qtile/libqtile/scripts/check.py", line 122, in check_config
        config.load()
      File "/home/runner/work/qtile/qtile/libqtile/confreader.py", line 136, in load
        config = importlib.import_module(name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 999, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/tmp/tmp91v98bz1/config.py", line 2, in <module>
        from libqtile.widget.base import ThreadPoolText
    ImportError: cannot import name 'ThreadPoolText' from 'libqtile.widget.base' (/home/runner/work/qtile/qtile/libqtile/widget/base.py)

IMO, this kind of transitive rename is a "wontfix" since we don't expect to
have these types of things often. I'm going to drop the old one and then we
won't get the crash any more.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>