widgets: don't re-draw after finalization
We've seen a lot of error reports recently with:

2021-02-26 23:09:02,693 ERROR libqtile
manager.py:get_interesting_pid():L598 Got an exception in getting the
window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line
596, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcbq.py",
line 610, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcbq.py",
line 703, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in
GetProperty
    return self.send_request(20, buf, GetPropertyCookie,
is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in
send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in
wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 556, in
invalid
    raise XcffibException("Invalid connection.")
xcffib.XcffibException: Invalid connection.
2021-02-26 23:09:02,702 ERROR libqtile base.py:on_done():L542 Failed to
reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line
534, in on_done
    self.update(result)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line
550, in update
    old_width = self.layout.width
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in
width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 132,
in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer,
not NoneType
2021-02-26 23:09:02,708 WARNING libqtile lifecycle.py:_atexit():L34
Restarting Qtile with os.execv(...)

(from the mailing list) or similar stack traces in #2197 and #2167

The crashes are all for reports of unrelated bugs, but have complaint
PangoLayout in them. I think (?) that the underlying problem here is that we're
finalizing the layout and then trying to draw to it from one of our scheduled
tasks.

While LoopContext.__aexit__() tries to cancel all tasks, that' isn't
necessarily guaranteed (and the same with futures if e.g. they're currently
running).

So, the widgets need to be smart enough not to draw if they've already been
finalized. It turns out that *all* widgets need these smarts, but let's
start with TextBox for now, since PangoLayout is the thing complaining the
most in peoples' reports.

I'm still trying to figure out how to test this, but I figured I'd send
these two patches across since we're seeing a lot of this noise.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>