Add returns to lazy.function and qtile.core.function
When using lazy.function for example to set a start function to a mouse
Drag, previously this would result in an error message like this:
Traceback (most recent call last):
  File "/home/ole/.local/pipx/venvs/qtile/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 334, in _xpoll
    self.handle_event(event)
  File "/home/ole/.local/pipx/venvs/qtile/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 301, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/home/ole/.local/pipx/venvs/qtile/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 682, in handle_ButtonPress
    self.qtile.process_button_click(button_code, state, event.event_x, event.event_y)
  File "/home/ole/.local/pipx/venvs/qtile/lib/python3.11/site-packages/libqtile/core/manager.py", line 856, in process_button_click
    self._drag = (x, y, val[0], val[1], m.commands)
                        ~~~^^^
TypeError: 'NoneType' object is not subscriptable

This was because libqtile.command.base.function didn't actually return
anything. This commit simply adds a return keyword to it.