add cp3.13 to the release process
I had to expand the glob here because manylinux ships a cp313-cp313t with
the free-threaded ABI, and we cannot compile against that (yet):

                In file included from
    build/temp.linux-x86_64-cpython-313t/pywayland._ffi.c:57:
    /opt/_internal/cpython-3.13.5-nogil/include/python3.13t/Python.h:51:4:
    error: #error "The limited API is not currently supported in the free-
    threaded build"
                   51 | #  error "The limited API is not currently supported in
    the free-threaded build"

We will have to figure out something for this when we want to build against
free-threaded, but for now it's not an option, so let's ignore it. (Maybe
wayc will help here? :)

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>