layout/screensplit: fix next/previous methods
With the next/previous test in the next patch, there's an error:

    FAILED test/layouts/test_common.py::test_next_previous[1-wayland-ScreenSplit] - libqtile.command.base.CommandException: AttributeError: <class 'libqtile.layout.screensplit.ScreenSplit'> has no attribute next

ScreenSplit really doesn't have a next or previous attribute, so this is
just a bug. Define ScreenSplit next and previous as the currently selected
layout's next and previous.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>