improve license specification in pyproject.toml
Our license is the MIT license. Let's use the "new" PEP0639 formatting for
it.

Also remove the license specifier in the classifiers, because:

    raise InvalidConfigError(
        setuptools.errors.InvalidConfigError: License classifiers have been superseded by license expressions (see https://peps.python.org/pep-0639/). Please remove:

        License :: OSI Approved :: MIT License
        [end of output]

Fixes #5233

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>