backends: fix idle_* type checking
Here's a whole slew of IdleNotifier type checking errors:

    libqtile/backend/base/core.py:154: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/backend/base/core.py:159: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/backend/base/core.py:166: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/backend/base/window.py:587: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/backend/base/window.py:592: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/core/manager.py:193: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/core/manager.py:195: error: "Core" has no attribute "idle_notifier"  [attr-defined]
    libqtile/core/manager.py:197: error: "Core" has no attribute "idle_notifier"  [attr-defined]
    libqtile/core/manager.py:857: error: "Core" has no attribute "idle_inhibitor_manager"  [attr-defined]
    libqtile/backend/wayland/core.py:844: error: "IdleNotifier" has no attribute "handle_timeout"  [attr-defined]
    libqtile/backend/wayland/core.py:846: error: "IdleNotifier" has no attribute "handle_resume"  [attr-defined]
    libqtile/backend/wayland/core.py:855: error: "IdleInhibitorManager[Inhibitor]" has no attribute "add_extension_inhibitor"  [attr-defined]
    libqtile/backend/wayland/core.py:860: error: "IdleInhibitorManager[Inhibitor]" has no attribute "remove_extension_inhibitor"; maybe "remove_window_inhibitor" or "remove_inhibitor"?  [attr-defined]
    libqtile/backend/wayland/core.py:286: error: Incompatible types in assignment (expression has type "libqtile.backend.wayland.idle_inhibit.IdleInhibitorManager", variable has type "libqtile.backend.base.idle_inhibit.IdleInhibitorManager[Inhibitor]")  [assignment]
    libqtile/backend/x11/core.py:332: error: "IdleNotifier" has no attribute "check_event"  [attr-defined]
    libqtile/backend/wayland/core.py:844: error: "IdleNotifier" has no attribute "handle_timeout"  [attr-defined]
    libqtile/backend/wayland/core.py:846: error: "IdleNotifier" has no attribute "handle_resume"  [attr-defined]
    libqtile/backend/wayland/core.py:855: error: "IdleInhibitorManager[Any]" has no attribute "add_extension_inhibitor"  [attr-defined]
    libqtile/backend/wayland/core.py:860: error: "IdleInhibitorManager[Any]" has no attribute "remove_extension_inhibitor"; maybe "remove_window_inhibitor" or "remove_inhibitor"?  [attr-defined]

No real bugs here (probably because there's actual tests for this code?),
but it's nice to have the typing all line up.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>