port Moc to use call_process() entirely
This way we don't need to monkey patch subprocess.Popen, and can avoid:

    FAILED test/widgets/test_moc.py::test_moc_button_presses[1-x11] - AssertionError: Error launching qtile, traceback:
    Traceback (most recent call last):
      File "/home/runner/work/qtile/qtile/test/helpers.py", line 191, in run_qtile
        kore = self.backend.create()
      File "/home/runner/work/qtile/qtile/test/helpers.py", line 111, in create
        return self.core(*self.args)
               ~~~~~~~~~^^^^^^^^^^^^
      File "/home/runner/work/qtile/qtile/libqtile/backend/x11/core.py", line 84, in __init__
        self.conn = xcbq.Connection(display_name)
                    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
      File "/home/runner/work/qtile/qtile/libqtile/backend/x11/xcbq.py", line 459, in __init__
        self.cursors = Cursors(self)
                       ~~~~~~~^^^^^^
      File "/home/runner/work/qtile/qtile/libqtile/backend/x11/xcursors.py", line 94, in __init__
        self.xcursor = self._setup_xcursor_binding()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/home/runner/work/qtile/qtile/libqtile/backend/x11/xcursors.py", line 106, in _setup_xcursor_binding
        lib = find_library(DynamicLibraries.XCBCURSOR)
      File "/home/runner/work/qtile/qtile/libqtile/__init__.py", line 70, in find_library
        return ctypes.util.find_library(key.value)
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/ctypes/util.py", line 341, in find_library
        return _findSoname_ldconfig(name) or \
               ~~~~~~~~~~~~~~~~~~~~^^^^^^
      File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/ctypes/util.py", line 301, in _findSoname_ldconfig
        with subprocess.Popen(['/sbin/ldconfig', '-p'],
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
                              stdin=subprocess.DEVNULL,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                              stderr=subprocess.DEVNULL,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                              stdout=subprocess.PIPE,
                              ^^^^^^^^^^^^^^^^^^^^^^^
                              env={'LC_ALL': 'C', 'LANG': 'C'}) as p:
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: MockMocpProcess.run() got an unexpected keyword argument 'stdin'

failing to load xcb-cursors.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>