don't use wayland backend in x11 tests
We were previously using `manager_nospawn`, which is a fixture that enables
the test for both backends, even though this test is x11 specific. You can
see this with the failed test name+params here:

    FAILED test/backend/x11/test_window.py::test_urgent_hook_fire[wayland-2]

instead, let's introduce our own xmanager_nospawn, and use that.

This is the other half of #4762

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>